#JPA Setting
#spring.jpa.hibernate.ddl-auto = update

#spring.datasource.url=jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=admin1

#Add h2 database changes
##################################################

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb  # In-memory database
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.platform=h2

# Enable H2 Console
spring.h2.console.enabled=true 
spring.h2.console.path=/h2-console

# Hibernate Configuration (Optional)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

